### ISSUE TITLE
Codestar Connection

### ISSUE THREAD

**Issue by ivancasco-sg** [StratusGrid/terraform-aws-multiaccount-pipeline#11]
https://github.com/StratusGrid/terraform-aws-multiaccount-pipeline/blob/8b1ab76f89dfa05adb7cfe5d55677cadfeb54a7a/-inputs.tf#L89-L93

[cp_source_codestar_connection_arn](https://github.com/StratusGrid/terraform-aws-multiaccount-pipeline#input_cp_source_codestar_connection_arn) is documented as not required, as it has an empty default value on the ./-inputs.tf file. It should be a required variable, as the rest of the code does not implement the creation of a codestar resource, and the module fails without it.

**Comment by chrischildresssg** [comment]
@ivancasco-sg , I believe the module only fails if neither a codestar connection nor a source s3 bucket is specified - it just needs one or the other.  Does that sound correct to you?  Perhaps what we need here is a bit more clear documentation and input validation rules?

**Comment by borjalopez-sg** [comment]
@chrischildresssg @wesleykirklandsg I thought of creating a new codestar connection in case both inputs were empty. Update the documentation to clarify it too. Does it make sense to you all?

**Comment by wesleykirklandsg** [comment]
@borjalopez-sg @chrischildresssg @ivancasco-sg See this PR for fixing this issue and bringing it into current module standards.

https://github.com/StratusGrid/terraform-aws-multiaccount-pipeline/pull/12
