### ISSUE TITLE
Folder Paths Should not be statically coded in CodeBuild

### ISSUE THREAD

**Issue by StratusChris** [StratusGrid/terraform-aws-multiaccount-pipeline#3]
## Expected Behavior
This module should be able to work regardless of the folder path being used for the terraform it applies.

## Actual Behavior
The CodeBuild has both /init-tfvars/ and /apply-tfvars/ paths statically coded in the codebuild-terraform.tf file.

**Comment by wesleykirklandsg** [comment]
Resolved under 1fc5834c7cee2eb57f754897c9fa8bfc41ff7fd4
