### ISSUE TITLE
Make better use of the environments map

### ISSUE THREAD

**Issue by StratusChris** [StratusGrid/terraform-aws-multiaccount-pipeline#4]
## Expected Behavior
We should make better use of information in the cb_accounts_map instead of having cb_accounts_map, environment_names, cb_iam_role, and cp_tf_manual_approval that all have to have matching names etc.

## Actual Behavior
Currently, we have a number of different variables that all need to match.

**Comment by wesleykirklandsg** [comment]
@StratusChris cb_iam_role will be removed in v2.

I have removed environment_names under 5f7d8e6419acfcc27c3781acc11eae8f2be93cc4 and I'm extracting them from the hashtable map now. cb_tf_manual has been replaced with a key value under cb_accounts_map and that is fixed under 7c78c34360954036a2cadfbfdbcb35f67f71d59e
